substitutions:
  id: "1"
  name: motor-${id}
  friendly_name: "Neato Motor ${id}"
  project_name: "CodeMakesItGo.Motor"
  project_version: "1.0.0"

packages:
  board: github://CodeMakesItGo/NeatoFx_Public/Controllers/NeatoMotor/boards/rev3.yaml@main
