---
version: 2
updates:
  - package-ecosystem: github-actions
    labels:
      - "dependencies"
      - "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    labels:
      - "dependencies"
      - "npm"
    directory: "/"
    schedule:
      interval: "daily"
