import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'link',
      label: 'Made for ESPHome',
      href: '/made-for-esphome',
    },
    {
      type: 'category',
      label: 'Device Type',
      collapsed: false,
      collapsible: false,
      items: [
        {type: 'link', label: 'Dimmers', href: '/type/dimmer'},
        {type: 'link', label: 'Lights & LEDs', href: '/type/light'},
        {type: 'link', label: 'Miscellaneous Devices', href: '/type/misc'},
        {type: 'link', label: 'Plugs & Sockets', href: '/type/plug'},
        {type: 'link', label: 'Relays', href: '/type/relay'},
        {type: 'link', label: 'Sensors', href: '/type/sensor'},
        {type: 'link', label: 'Switches', href: '/type/switch'},
      ],
    },
    {
      type: 'category',
      label: 'Electrical Standard',
      collapsed: false,
      collapsible: false,
      items: [
        {type: 'link', label: 'AU Devices', href: '/standards/au'},
        {type: 'link', label: 'BR Devices', href: '/standards/br'},
        {type: 'link', label: 'EU Devices', href: '/standards/eu'},
        {type: 'link', label: 'Global Devices', href: '/standards/global'},
        {type: 'link', label: 'IN Devices', href: '/standards/in'},
        {type: 'link', label: 'UK Devices', href: '/standards/uk'},
        {type: 'link', label: 'US Devices', href: '/standards/us'},
      ],
    },
    {
      type: 'category',
      label: 'Microcontroller',
      collapsed: false,
      collapsible: false,
      items: [
        {type: 'link', label: 'BK72xx', href: '/board/bk72xx'},
        {type: 'link', label: 'ESP32', href: '/board/esp32'},
        {type: 'link', label: 'ESP8266', href: '/board/esp8266'},
        {type: 'link', label: 'RP2040', href: '/board/rp2040'},
        {type: 'link', label: 'RTL87xx', href: '/board/rtl87xx'},
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      collapsible: false,
      items: [
        {type: 'link', label: 'Adding Devices', href: '/devices/adding-devices'},
        {type: 'link', label: 'Prepare a device with tuya-convert', href: '/devices/tuya-convert'},
      ],
    },
    {
      type: 'category',
      label: 'Hosted By',
      collapsed: false,
      collapsible: false,
      items: [
        {type: 'link', label: 'Netlify', href: 'https://netlify.com/'},
      ],
    },
    {
      type: 'category',
      label: 'All Devices',
      collapsed: true,
      className: 'hide-all-devices',
      items: [
        {type: 'autogenerated', dirName: '.'}
      ]
    }
  ],
};

export default sidebars;
