substitutions:
  id_prefix: sprl

esphome:
  name: sprinkler
  friendly_name: Sprinkler System
  name_add_mac_suffix: true
  project:
    name: "thebeaverdam.sprinkler"
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

mdns:

api:

ota:
  - platform: esphome

wifi:
  ap: {}

captive_portal:

improv_serial:

dashboard_import:
  package_import_url: github://thebeaverdam/ESP32_SprinklerSystem/firmware/sprinkler.yaml

web_server:

sprinkler:
  - id: ${id_prefix}_sprinklers
    main_switch: "Sprinklers"
    auto_advance_switch: "Sprinklers Auto Advance"
    valves:
      - valve_switch: "Zone 1"
        enable_switch: "Enable Zone 1"
        valve_switch_id: lawn_sprinkler_valve_sw1
      - valve_switch: "Zone 2"
        enable_switch: "Enable Zone 2"
        valve_switch_id: lawn_sprinkler_valve_sw2
      - valve_switch: "Zone 3"
        enable_switch: "Enable Zone 3"
        valve_switch_id: lawn_sprinkler_valve_sw3
      - valve_switch: "Zone 4"
        enable_switch: "Enable Zone 4"
        valve_switch_id: lawn_sprinkler_valve_sw4
      - valve_switch: "Zone 5"
        enable_switch: "Enable Zone 5"
        valve_switch_id: lawn_sprinkler_valve_sw5
      - valve_switch: "Zone 6"
        enable_switch: "Enable Zone 6"
        valve_switch_id: lawn_sprinkler_valve_sw6
      - valve_switch: "Zone 7"
        enable_switch: "Enable Zone 7"
        valve_switch_id: lawn_sprinkler_valve_sw7
      - valve_switch: "Zone 8"
        enable_switch: "Enable Zone 8"
        valve_switch_id: lawn_sprinkler_valve_sw8

switch:
  - platform: gpio
    id: lawn_sprinkler_valve_sw1
    pin: GPIO19
  - platform: gpio
    id: lawn_sprinkler_valve_sw2
    pin: GPIO18
  - platform: gpio
    id: lawn_sprinkler_valve_sw3
    pin: GPIO17
  - platform: gpio
    id: lawn_sprinkler_valve_sw4
    pin: GPIO16
  - platform: gpio
    id: lawn_sprinkler_valve_sw5
    pin: GPIO32
  - platform: gpio
    id: lawn_sprinkler_valve_sw6
    pin: GPIO33
  - platform: gpio
    id: lawn_sprinkler_valve_sw7
    pin: GPIO25
  - platform: gpio
    id: lawn_sprinkler_valve_sw8
    pin: GPIO26

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
  - platform: uptime
    name: Uptime
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Connection Status"