substitutions:
  id: "1"
  name: audio-${id}
  friendly_name: "NEATO Audio ${id}"
  project_name: "CodeMakesItGo.Audio50"
  project_version: "1.0.0"

packages:
  board: github://CodeMakesItGo/NeatoFx_Public/Audio/NeatoAudio50/boards/rev2_4.yaml@main
  rftx:  github://CodeMakesItGo/NeatoFx_Public/Audio/NeatoAudio50/boards/rftx_outputs.yaml@main
