substitutions:
  id: "1"
  name: target-${id}
  friendly_name: "NEATO Target ${id}"
  project_name: "CodeMakesItGo.Target"
  project_version: "1.0.0"

packages:
  board: github://CodeMakesItGo/NeatoFx_Public/Targets/NeatoTargetIR/boards/rev3.yaml@main
